language: ruby
rvm:
- 2.2.5

# before install
before_install:
- git clone https://github.com/naokiy/tefuda.suku.name-jekyll.git jekyll

install:
- cd jekyll
- bundle install

script:
- cp _posts jekyll/
- cd jekyll
- bundle exec jekyll build --trace

branches:
  except:
  - master

sudo: false
