language: ruby

rvm:
- 2.2.5

before_install:
- git clone https://github.com/naokiy/tefuda.suku.name-jekyll.git jekyll

install:
- cp -r _posts jekyll/
- openssl aes-256-cbc -K $encrypted_0b90d33a0dab_key -iv $encrypted_0b90d33a0dab_iv
  -in .travis/.deploy_key.enc -out jekyll/.deploy_key -d
- cd jekyll
- bash ./scripts/install.sh

cache: bundler

script:
- bash ./scripts/build.sh

after_success:
- bash ./scripts/deploy.sh

sudo: false
